# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.cache/wt [current_project]
set_property parent.project_path C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo c:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/sources_1/new/Adders/Add_Substract_4.vhd
  C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/sources_1/new/Adders/Adder_3.vhd
  C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/sources_1/new/Multiplexers/Decoder_2_to_4.vhd
  C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/sources_1/new/Multiplexers/Decoder_3_to_8.vhd
  C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/sources_1/new/Adders/FA.vhd
  C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/sources_1/new/Adders/HA.vhd
  C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/sources_1/new/Instruction_decoder.vhd
  C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/sources_1/new/LUT_16_7_Seg.vhd
  C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/sources_1/new/Multiplexers/Mux_2_way_3_bit.vhd
  C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/sources_1/new/Multiplexers/Mux_2_way_4_bit.vhd
  C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/sources_1/new/Multiplexers/Mux_8_way_4_bit.vhd
  C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/sources_1/new/Nano_processor.vhd
  C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/sources_1/new/Program_counter.vhd
  C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/sources_1/new/Adders/RCA_4.vhd
  C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/sources_1/new/ROM.vhd
  C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/sources_1/new/RegisterBank/Register_4.vhd
  C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/sources_1/new/RegisterBank/Register_bank.vhd
  C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/sources_1/new/Counters/Slow_Clk.vhd
  C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/sources_1/new/Main_unit.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/constrs_1/new/Basys3Labs.xdc
set_property used_in_implementation false [get_files C:/Users/Eutech/Documents/FinalNanoProcessor/FinalNanoProcessor.srcs/constrs_1/new/Basys3Labs.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Main_unit -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Main_unit.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Main_unit_utilization_synth.rpt -pb Main_unit_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
